overrides:
  nodemailer@<=8.0.4: '>=8.0.5'
  nodemailer@<=8.0.7: '>=8.0.8'
  nodemailer@<=8.0.8: '>=8.0.9'
  path-to-regexp@>=8.0.0 <8.4.0: '>=8.4.0'
  qs@>=6.11.1 <=6.15.1: '>=6.15.2'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
