const Routes = {
	Root: "/",
	Privacy: "/privacy",
	privacyEN: "/privacy/en",
	privacyNL: "/privacy/nl",
	CountDown: "/countdown",
	Project: "/project",
	Login: "/login",
	ProjectenPage: "/project",
	ProjectenPageOld: "/projecten",
	ProjectForm: "/project/form",
	ProjectFormOld: "/project-form",
	ProjectenPageDetails: "/project/:id",
	Info: "/info",
	Awards: "/awards",
	uMoeder: "/u/Moeder",
	NotFound: "/404",
	LiveVoting: "/live/voting/show/nooneWillLook/live_vote",
	News: "/news",
};
export default Routes;
