name: Deploy live website

on:
    push:
        branches: [FRONT-main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npm ci
              working-directory: Frontend
            - run: npm run build
              working-directory: Frontend
            - uses: SamKirkland/FTP-Deploy-Action@v4.3.6
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_KEY }}
                  local-dir: Frontend/dist/
                  server-dir: /www/
                  dangerous-clean-slate: true
