name: Deploy live website

on:
    push:
        branches: [FRONT-main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npm ci
              working-directory: Frontend
            - run: npm run build
              working-directory: Frontend
            - uses: SamKirkland/FTP-Deploy-Action@v4.3.6
              with:
                  server: ${{ secrets.FTP_SERVER }}
                  username: ${{ secrets.FTP_USERNAME_2 }}
                  password: ${{ secrets.FTP_PASSWORD_2 }}
                  local-dir: Frontend/dist/
                  server-dir: /www/
                  dangerous-clean-slate: true
